Repository 5ingMaryho/OingLogistics, pull requests merged in 2025-03, with the labels that each got.

#8 [eureka] : 유레카 설정 추가
  eureka-service/.gitattributes
  eureka-service/build.gradle
  eureka-service/gradle/wrapper/gradle-wrapper.jar
  eureka-service/gradle/wrapper/gradle-wrapper.properties
  eureka-service/gradlew
  eureka-service/gradlew.bat
  eureka-service/settings.gradle
  eureka-service/src/main/java/com/oingmaryho/infrastructure/eureka_service/EurekaServiceApplication.java
  eureka-service/src/test/java/com/oingmaryho/infrastructure/eureka_service/EurekaServiceApplicationTests.java
Labels: ✏ feat

#10 [gateway] : Gateway 초기 설정
  gateway-service/.gitattributes
  gateway-service/.gitignore
  gateway-service/build.gradle
  gateway-service/gradle/wrapper/gradle-wrapper.jar
  gateway-service/gradle/wrapper/gradle-wrapper.properties
  gateway-service/gradlew
  gateway-service/gradlew.bat
  gateway-service/settings.gradle
  gateway-service/src/main/java/com/oingmaryho/infrastructure/gateway_service/GatewayServiceApplication.java
  gateway-service/src/main/java/com/oingmaryho/infrastructure/gateway_service/config/GatewayConfig.java
  gateway-service/src/main/java/com/oingmaryho/infrastructure/gateway_service/filter/JwtAuthFilter.java
  gateway-service/src/test/java/com/oingmaryho/infrastructure/gateway_service/GatewayServiceApplicationTests.java
Labels: ✏ feat

#14 [Order] : 주문 프로젝트 만들기
  order-service/.gitattributes
  order-service/HELP.md
  order-service/build.gradle
  order-service/gradle/wrapper/gradle-wrapper.jar
  order-service/gradle/wrapper/gradle-wrapper.properties
  order-service/gradlew
  order-service/gradlew.bat
  order-service/settings.gradle
  order-service/src/main/java/com/oingmaryho/business/orderservice/OrderServiceApplication.java
  order-service/src/test/java/com/oingmaryho/business/orderservice/OrderServiceApplicationTests.java
Labels: ✏ feat

#25 [Delivery] : 배송 프로젝트 만들기, .gitignore 수정
  .gitignore
  delivery-service/.gitattributes
  delivery-service/HELP.md
  delivery-service/build.gradle
  delivery-service/gradle/wrapper/gradle-wrapper.jar
  delivery-service/gradle/wrapper/gradle-wrapper.properties
  delivery-service/gradlew
  delivery-service/gradlew.bat
  delivery-service/settings.gradle
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/DeliveryServiceApplication.java
  delivery-service/src/main/resources/application.yml
  delivery-service/src/test/java/com/oingmaryho/business/delivery_service/DeliveryServiceApplicationTests.java
Labels: ✏ feat, 🛠 fix

#27 [Eureka] : build.gradle 수정
  eureka-service/build.gradle
  gateway-service/build.gradle
  gateway-service/src/main/java/com/oingmaryho/infrastructure/gateway_service/filter/JwtAuthFilter.java
Labels: 🛠 fix

#28 [Docs] : PR 템플릿 수정
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 📝 docs

#41 [Company] : 업체 프로젝트 만들기
  company-service/.gitattributes
  company-service/HELP.md
  company-service/build.gradle
  company-service/gradle/wrapper/gradle-wrapper.jar
  company-service/gradle/wrapper/gradle-wrapper.properties
  company-service/gradlew
  company-service/gradlew.bat
  company-service/settings.gradle
  company-service/src/main/java/com/oingmaryho/business/companyservice/CompanyServiceApplication.java
  company-service/src/main/resources/application.yml
  company-service/src/test/java/com/oingmaryho/business/companyservice/CompanyServiceApplicationTests.java
Labels: ✏ feat

#33 [Product]: 상품 프로젝트 만들기
  product-service/.gitattributes
  product-service/build.gradle
  product-service/gradle/wrapper/gradle-wrapper.jar
  product-service/gradle/wrapper/gradle-wrapper.properties
  product-service/gradlew
  product-service/gradlew.bat
  product-service/settings.gradle
  product-service/src/main/java/com/oingmaryho/business/productservice/ProductServiceApplication.java
  product-service/src/main/resources/application.yml
  product-service/src/test/java/com/oingmaryho/business/productservice/ProductServiceApplicationTests.java
Labels: ✏ feat

#50 [Hub] : 허브 프로젝트 만들기
  hub-service/.gitattributes
  hub-service/HELP.md
  hub-service/build.gradle
  hub-service/gradle/wrapper/gradle-wrapper.jar
  hub-service/gradle/wrapper/gradle-wrapper.properties
  hub-service/gradlew
  hub-service/gradlew.bat
  hub-service/settings.gradle
  hub-service/src/main/java/com/oingmaryho/business/hubservice/HubServiceApplication.java
  hub-service/src/main/resources/application.yml
  hub-service/src/test/java/com/oingmaryho/business/hubservice/HubServiceApplicationTests.java
Labels: ✏ feat

#60 [User] : 사용자 프로젝트 만들기
  user-service/.gitattributes
  user-service/.gitignore
  user-service/HELP.md
  user-service/build.gradle
  user-service/gradle/wrapper/gradle-wrapper.jar
  user-service/gradle/wrapper/gradle-wrapper.properties
  user-service/gradlew
  user-service/gradlew.bat
  user-service/settings.gradle
  user-service/src/main/java/com/oringmaryho/business/userservice/UserServiceApplication.java
  user-service/src/main/resources/application.yml
  user-service/src/test/java/com/oringmaryho/business/userservice/UserServiceApplicationTests.java
Labels: ✏ feat

#70 [User] : 사용자 프로젝트 만들기
  user-service/.gitignore
Labels: ⚙ refactor

#77 [User] : Controller, Service, Repository 생성 (일반 사용자)
  user-service/build.gradle
  user-service/src/main/java/com/oringmaryho/business/userservice/application/UserApplicationMapper.java
  user-service/src/main/java/com/oringmaryho/business/userservice/application/UserService.java
  user-service/src/main/java/com/oringmaryho/business/userservice/application/dto/request/UserSearchRequestServiceDto.java
  user-service/src/main/java/com/oringmaryho/business/userservice/application/dto/request/UserSignInRequestServiceDto.java
  user-service/src/main/java/com/oringmaryho/business/userservice/application/dto/request/UserSignUpRequestServiceDto.java
  user-service/src/main/java/com/oringmaryho/business/userservice/application/dto/request/UserSlackConfirmRequestServiceDto.java
  user-service/src/main/java/com/oringmaryho/business/userservice/application/dto/response/UserSearchResponseServiceDto.java
  user-service/src/main/java/com/oringmaryho/business/userservice/application/dto/response/UserSignInResponseServiceDto.java
  user-service/src/main/java/com/oringmaryho/business/userservice/domain/BaseEntity.java
  user-service/src/main/java/com/oringmaryho/business/userservice/domain/User.java
  user-service/src/main/java/com/oringmaryho/business/userservice/domain/UserConfirmStatus.java
  user-service/src/main/java/com/oringmaryho/business/userservice/domain/UserRoleType.java
  user-service/src/main/java/com/oringmaryho/business/userservice/infrastructure/UserRepository.java
  user-service/src/main/java/com/oringmaryho/business/userservice/presentation/UserController.java
  user-service/src/main/java/com/oringmaryho/business/userservice/presentation/UserPresentationMapper.java
  user-service/src/main/java/com/oringmaryho/business/userservice/presentation/dto/request/UserSearchRequestDto.java
  user-service/src/main/java/com/oringmaryho/business/userservice/presentation/dto/request/UserSignInRequestDto.java
  user-service/src/main/java/com/oringmaryho/business/userservice/presentation/dto/request/UserSignUpRequestDto.java
  user-service/src/main/java/com/oringmaryho/business/userservice/presentation/dto/request/UserSlackConfirmRequestDto.java
  user-service/src/main/java/com/oringmaryho/business/userservice/presentation/dto/response/UserSearchResponseDto.java
  user-service/src/main/java/com/oringmaryho/business/userservice/presentation/dto/response/UserSignInResponseDto.java
Labels: ✏ feat

#75 [Delivery] : Controller - Service - Repository 연결 (마스터 외 사용자)
  delivery-service/build.gradle
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/DeliveryServiceApplication.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/DeliveryApplicationMapper.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/DeliveryService.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/dto/request/DeliveryCreationRequestServiceDto.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/dto/request/DeliveryDeletionRequestServiceDto.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/dto/request/DeliveryDetailRequestServiceDto.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/dto/request/DeliveryRouteDetailRequestServiceDto.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/dto/request/DeliveryRouteSearchRequestServiceDto.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/dto/request/DeliverySearchRequestServiceDto.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/dto/request/DeliveryUpdateRequestServiceDto.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/dto/request/DeliveryUpdateStatusRequestServiceDto.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/dto/response/DeliveryCreationResponseServiceDto.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/dto/response/DeliveryDetailResponseServiceDto.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/dto/response/DeliveryResponseServiceDto.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/dto/response/DeliveryRouteDetailResponseServiceDto.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/dto/response/DeliveryRouteResponseServiceDto.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/dto/response/DeliveryUpdateResponseServiceDto.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/dto/response/DeliveryUpdateStatusResponseServiceDto.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/config/JpaAuditingConfig.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/domain/BaseEntity.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/domain/Delivery.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/domain/DeliveryManagerType.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/domain/DeliveryManger.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/domain/DeliveryRoute.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/domain/DeliveryRouteStatus.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/domain/DeliveryStatus.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/infrastructure/DeliveryRepository.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/presentation/DeliveryController.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/presentation/DeliveryPresentationMapper.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/presentation/dto/request/DeliveryCreationRequestDto.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/presentation/dto/request/DeliveryRouteSearchRequestDto.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/presentation/dto/request/DeliverySearchRequestDto.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/presentation/dto/request/DeliveryUpdateRequestDto.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/presentation/dto/request/DeliveryUpdateStatusRequestDto.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/presentation/dto/response/DeliveryCreationResponseDto.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/presentation/dto/response/DeliveryDetailResponseDto.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/presentation/dto/response/DeliveryResponseDto.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/presentation/dto/response/DeliveryRouteDetailResponseDto.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/presentation/dto/response/DeliveryRouteResponseDto.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/presentation/dto/response/DeliveryUpdateResponseDto.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/presentation/dto/response/DeliveryUpdateStatusResponseDto.java
Labels: ✏ feat

#78 [Hub] : Hub Controller 및 관련 Dto 생성
  hub-service/src/main/java/com/oingmaryho/business/hubservice/presentation/HubController.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/presentation/HubRouteController.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/presentation/dto/request/HubRouteSearchRequestDto.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/presentation/dto/request/HubSearchRequestDto.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/presentation/dto/response/HubSearchResponseDto.java
Labels: ✏ feat

#79 [Order] : 주문 조회 기능 구현(마스터) #30
  order-service/build.gradle
  order-service/src/main/java/com/oingmaryho/business/orderservice/OrderServiceApplication.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/OrderApplicationMapper.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/OrderService.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/dto/OrderServiceDto.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/dto/OrdersServiceDto.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/config/CacheConfig.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/config/CacheType.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/config/pageable/PageableConfig.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/config/pageable/SortConstants.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/domain/BaseEntity.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/domain/Order.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/domain/OrderDetail.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/domain/Status.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/infrastructure/OrderRepository.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/presentation/OrderController.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/presentation/OrderPresentationMapper.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/presentation/dto/request/OrderSearchRequestDto.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/presentation/dto/response/OrderDetailDto.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/presentation/dto/response/OrderDto.java
  order-service/src/main/resources/logback.xml
  order-service/src/test/java/com/oingmaryho/business/orderservice/OrderServiceApplicationTests.java
  order-service/src/test/java/com/oingmaryho/business/orderservice/application/OrderServiceTest.java
Labels: ✏ feat, 📑 test

#81 [Order] : 주문 상세 조회 기능 구현(마스터) #30
  .gitignore
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/OrderApplicationMapper.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/OrderService.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/exception/ErrorCode.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/exception/GlobalExceptionHandler.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/exception/OrderException.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/presentation/OrderController.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/presentation/OrderPresentationMapper.java
  order-service/src/test/java/com/oingmaryho/business/orderservice/application/OrderServiceTest.java
Labels: ✏ feat, 🛠 fix

#85 [Product] : 상품 Controller 및 RequestDto, ResponseDto
  product-service/build.gradle
  product-service/src/main/java/com/oingmaryho/business/productservice/ProductServiceApplication.java
  product-service/src/main/java/com/oingmaryho/business/productservice/application/ProductApplicationMapper.java
  product-service/src/main/java/com/oingmaryho/business/productservice/application/ProductService.java
  product-service/src/main/java/com/oingmaryho/business/productservice/application/dto/request/ProductDetailsSearchRequestServiceDto.java
  product-service/src/main/java/com/oingmaryho/business/productservice/application/dto/response/ProductDetailsSearchResponseServiceDto.java
  product-service/src/main/java/com/oingmaryho/business/productservice/config/JpaAuditingConfig.java
  product-service/src/main/java/com/oingmaryho/business/productservice/config/pageable/PageableConfig.java
  product-service/src/main/java/com/oingmaryho/business/productservice/config/pageable/SortConstants.java
  product-service/src/main/java/com/oingmaryho/business/productservice/domain/BaseEntity.java
  product-service/src/main/java/com/oingmaryho/business/productservice/domain/Product.java
  product-service/src/main/java/com/oingmaryho/business/productservice/domain/repository/ProductRepository.java
  product-service/src/main/java/com/oingmaryho/business/productservice/domain/repository/ProductRepositoryImpl.java
  product-service/src/main/java/com/oingmaryho/business/productservice/infrastructure/ProductJpaRepository.java
  product-service/src/main/java/com/oingmaryho/business/productservice/infrastructure/ProductQueryDslRepository.java
  product-service/src/main/java/com/oingmaryho/business/productservice/presentation/ProductFeignClientController.java
  product-service/src/main/java/com/oingmaryho/business/productservice/presentation/ProductPresentationMapper.java
  product-service/src/main/java/com/oingmaryho/business/productservice/presentation/dto/response/ProductDetailsSearchResponseDto.java
Labels: ✏ feat

#87 [User] : 일반 사용자 회원가입 구현
  .gitignore
  user-service/src/main/java/com/oringmaryho/business/userservice/application/UserAdminService.java
  user-service/src/main/java/com/oringmaryho/business/userservice/application/UserApplicationMapper.java
  user-service/src/main/java/com/oringmaryho/business/userservice/application/UserMasterService.java
  user-service/src/main/java/com/oringmaryho/business/userservice/application/UserService.java
  user-service/src/main/java/com/oringmaryho/business/userservice/application/dto/request/UserAdminCreateRequestServiceDto.java
  user-service/src/main/java/com/oringmaryho/business/userservice/application/dto/request/UserAdminFindRequestServiceDto.java
  user-service/src/main/java/com/oringmaryho/business/userservice/application/dto/request/UserAdminGrantRoleRequestServiceDto.java
  user-service/src/main/java/com/oringmaryho/business/userservice/application/dto/request/UserAdminSearchRequestServiceDto.java
  user-service/src/main/java/com/oringmaryho/business/userservice/application/dto/request/UserAdminSignUpRequestServiceDto.java
  user-service/src/main/java/com/oringmaryho/business/userservice/application/dto/request/UserAdminUpdateRequestServiceDto.java
  user-service/src/main/java/com/oringmaryho/business/userservice/application/dto/request/UserAdminUpdateRoleRequestServiceDto.java
  user-service/src/main/java/com/oringmaryho/business/userservice/application/dto/request/UserMasterFindRequestServiceDto.java
  user-service/src/main/java/com/oringmaryho/business/userservice/application/dto/request/UserMasterSearchRequestServiceDto.java
  user-service/src/main/java/com/oringmaryho/business/userservice/application/dto/request/UserMasterSignUpRequestServiceDto.java
  user-service/src/main/java/com/oringmaryho/business/userservice/application/dto/request/UserMasterUpdateRequestServiceDto.java
  user-service/src/main/java/com/oringmaryho/business/userservice/application/dto/response/UserAdminSearchResponseServiceDto.java
  user-service/src/main/java/com/oringmaryho/business/userservice/application/dto/response/UserAdminUpdateRoleResponseServiceDto.java
  user-service/src/main/java/com/oringmaryho/business/userservice/application/dto/response/UserMasterSearchResponseServiceDto.java
  user-service/src/main/java/com/oringmaryho/business/userservice/config/JpaAuditingConfig.java
  user-service/src/main/java/com/oringmaryho/business/userservice/config/security/SecurityConfig.java
  user-service/src/main/java/com/oringmaryho/business/userservice/domain/User.java
  user-service/src/main/java/com/oringmaryho/business/userservice/infrastructure/UserRepository.java
  user-service/src/main/java/com/oringmaryho/business/userservice/presentation/UserAdminController.java
  user-service/src/main/java/com/oringmaryho/business/userservice/presentation/UserController.java
  user-service/src/main/java/com/oringmaryho/business/userservice/presentation/UserMasterController.java
  user-service/src/main/java/com/oringmaryho/business/userservice/presentation/UserPresentationMapper.java
  user-service/src/main/java/com/oringmaryho/business/userservice/presentation/dto/request/UserAdminCreateRequestDto.java
  user-service/src/main/java/com/oringmaryho/business/userservice/presentation/dto/request/UserAdminDeleteRequestServiceDto.java
  user-service/src/main/java/com/oringmaryho/business/userservice/presentation/dto/request/UserAdminDeleteRoleRequestServiceDto.java
  user-service/src/main/java/com/oringmaryho/business/userservice/presentation/dto/request/UserAdminFindRequestDto.java
  user-service/src/main/java/com/oringmaryho/business/userservice/presentation/dto/request/UserAdminGrantRoleRequestDto.java
  user-service/src/main/java/com/oringmaryho/business/userservice/presentation/dto/request/UserAdminSearchRequestDto.java
  user-service/src/main/java/com/oringmaryho/business/userservice/presentation/dto/request/UserAdminSignUpRequestDto.java
  user-service/src/main/java/com/oringmaryho/business/userservice/presentation/dto/request/UserAdminUpdateRequestDto.java
  user-service/src/main/java/com/oringmaryho/business/userservice/presentation/dto/request/UserAdminUpdateRoleRequestDto.java
  user-service/src/main/java/com/oringmaryho/business/userservice/presentation/dto/request/UserMasterSearchRequestDto.java
  user-service/src/main/java/com/oringmaryho/business/userservice/presentation/dto/request/UserMasterSignUpRequestDto.java
  user-service/src/main/java/com/oringmaryho/business/userservice/presentation/dto/request/UserMasterUpdateRequestDto.java
  user-service/src/main/java/com/oringmaryho/business/userservice/presentation/dto/response/UserAdminGrantRoleResponseDto.java
  user-service/src/main/java/com/oringmaryho/business/userservice/presentation/dto/response/UserAdminSearchResponseDto.java
  user-service/src/main/java/com/oringmaryho/business/userservice/presentation/dto/response/UserAdminUpdateResponseDto.java
  user-service/src/main/java/com/oringmaryho/business/userservice/presentation/dto/response/UserAdminUpdateRoleResponseDto.java
  user-service/src/main/resources/application.yml
  user-service/src/test/java/com/oringmaryho/business/userservice/application/UserServiceTest.java
Labels: ✏ feat, 📑 test, ⚙ refactor

#88 [Order] : 주문 수정 기능 구현(마스터)
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/OrderAdminService.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/OrderApplicationMapper.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/OrderFeignService.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/OrderService.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/dto/OrderDetailUpdateDto.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/dto/OrderDetailUpdateServiceDto.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/dto/OrderUpdateDto.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/dto/OrderUpdateServiceDto.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/domain/Order.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/domain/OrderDetail.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/exception/ErrorCode.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/presentation/OrderAdminController.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/presentation/OrderController.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/presentation/OrderFeignClientController.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/presentation/OrderPresentationMapper.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/presentation/dto/request/OrderDetailUpdateRequestDto.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/presentation/dto/request/OrderUpdateRequestDto.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/presentation/dto/response/OrderDetailResponseDto.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/presentation/dto/response/OrderResponseDto.java
  order-service/src/test/java/com/oingmaryho/business/orderservice/application/OrderServiceTest.java
Labels: ✏ feat, ⚙ refactor

#89 [Order] : 주문 삭제 기능 구현(마스터) #32
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/OrderAdminService.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/OrderApplicationMapper.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/dto/OrderDeleteDto.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/domain/Order.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/domain/OrderDetail.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/presentation/OrderAdminController.java
Labels: ✏ feat

#93 [User] : 관리자용 회원가입 기능 구현
  gateway-service/src/main/java/com/oingmaryho/infrastructure/gateway_service/config/GatewayConfig.java
  user-service/build.gradle
  user-service/src/main/java/com/oringmaryho/business/userservice/UserServiceApplication.java
  user-service/src/main/java/com/oringmaryho/business/userservice/application/UserAdminService.java
  user-service/src/main/java/com/oringmaryho/business/userservice/application/UserApplicationMapper.java
  user-service/src/main/java/com/oringmaryho/business/userservice/application/UserService.java
  user-service/src/main/java/com/oringmaryho/business/userservice/domain/BaseEntity.java
  user-service/src/main/java/com/oringmaryho/business/userservice/domain/User.java
  user-service/src/main/java/com/oringmaryho/business/userservice/domain/UserRoleType.java
  user-service/src/main/java/com/oringmaryho/business/userservice/presentation/UserAdminController.java
  user-service/src/main/java/com/oringmaryho/business/userservice/presentation/UserPresentationMapper.java
  user-service/src/main/resources/application.yml
  user-service/src/test/java/com/oringmaryho/business/userservice/application/UserAdminServiceTest.java
Labels: ✏ feat

#94 [Order] : 주문 코드 리팩토링 #91
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/dto/OrderDeleteDto.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/dto/OrderDetailUpdateDto.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/dto/OrderDetailUpdateServiceDto.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/dto/OrderServiceDto.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/dto/OrderUpdateDto.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/dto/OrderUpdateServiceDto.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/dto/mapper/OrderApplicationMapper.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/dto/request/OrderDeleteServiceDto.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/dto/request/OrderDetailUpdateRequestServiceDto.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/dto/request/OrderRequestServiceDto.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/dto/request/OrderUpdateRequestServiceDto.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/dto/request/OrdersRequestServiceDto.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/dto/response/OrderDetailUpdateResponseServiceDto.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/dto/response/OrderResponseServiceDto.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/dto/response/OrderUpdateResponseServiceDto.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/service/OrderAdminService.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/service/OrderFeignService.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/service/OrderService.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/domain/Order.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/domain/OrderDetail.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/presentation/OrderPresentationMapper.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/presentation/controller/OrderAdminController.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/presentation/controller/OrderController.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/presentation/controller/OrderFeignClientController.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/presentation/dto/mapper/OrderPresentationMapper.java
  order-service/src/test/java/com/oingmaryho/business/orderservice/application/OrderServiceTest.java
Labels: ⚙ refactor

#97 [Delivery] : 배송 경로 상세 조회, 검색, 배송 상세 조회
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/DeliveryAdminService.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/DeliveryService.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/dto/mapper/DeliveryApplicationMapper.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/infrastructure/DeliveryCustomRepository.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/infrastructure/DeliveryCustomRepositoryImpl.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/infrastructure/DeliveryRepository.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/presentation/DeliveryAdminController.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/presentation/DeliveryController.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/presentation/dto/mapper/DeliveryPresentationMapper.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/utils/PageableUtils.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/utils/QueryDslUtils.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/utils/SortConstants.java
Labels: ✏ feat

#98 [Hub] : 허브 생성 기능 구현(마스터)
  hub-service/build.gradle
  hub-service/src/main/java/com/oingmaryho/business/hubservice/application/HubAdminService.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/application/HubService.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/application/dto/mapper/HubApplicationMapper.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/application/dto/request/HubCreateRequestServiceDto.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/application/dto/response/HubCreateResponseServiceDto.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/domain/Address.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/domain/Hub.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/domain/repository/HubRepository.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/infrastructure/HubJpaRepository.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/infrastructure/HubQueryRepository.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/presentation/HubAdminController.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/presentation/HubController.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/presentation/dto/mapper/HubPresentationMapper.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/presentation/dto/request/HubCreateRequestDto.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/presentation/dto/response/HubCreateResponseDto.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/utils/PageableUtils.java
  hub-service/src/test/java/com/oingmaryho/business/hubservice/application/HubAdminServiceTest.java
  hub-service/src/test/java/com/oingmaryho/business/hubservice/application/HubServiceTest.java
Labels: ✏ feat, 📑 test

#99 [Order] : 주문 조회 기능 구현 #30
  order-service/build.gradle
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/dto/mapper/OrderApplicationMapper.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/service/OrderAdminService.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/service/OrderService.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/config/QueryDslConfig.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/presentation/controller/OrderController.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/utils/PageableUtils.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/utils/QueryDslUtils.java
Labels: ✏ feat

#102 [User] : 사용자 로그인 기능 구현#39
  gateway-service/build.gradle
  gateway-service/src/main/java/com/oingmaryho/infrastructure/gateway_service/config/GatewayConfig.java
  gateway-service/src/main/java/com/oingmaryho/infrastructure/gateway_service/config/RedisConfig.java
  gateway-service/src/main/java/com/oingmaryho/infrastructure/gateway_service/filter/JwtAuthFilter.java
  user-service/build.gradle
  user-service/docker-compose.yml
  user-service/src/main/java/com/oringmaryho/business/userservice/UserServiceApplication.java
  user-service/src/main/java/com/oringmaryho/business/userservice/application/UserService.java
  user-service/src/main/java/com/oringmaryho/business/userservice/config/security/RedisConfig.java
  user-service/src/main/java/com/oringmaryho/business/userservice/config/security/SecurityConfig.java
  user-service/src/main/java/com/oringmaryho/business/userservice/config/security/jwt/JwtTokenProvider.java
  user-service/src/main/java/com/oringmaryho/business/userservice/domain/BaseEntity.java
  user-service/src/main/java/com/oringmaryho/business/userservice/domain/User.java
  user-service/src/main/java/com/oringmaryho/business/userservice/exception/ErrorCode.java
  user-service/src/main/java/com/oringmaryho/business/userservice/exception/GlobalExceptionHandler.java
  user-service/src/main/java/com/oringmaryho/business/userservice/exception/UserException.java
  user-service/src/main/java/com/oringmaryho/business/userservice/infrastructure/UserRepository.java
  user-service/src/main/java/com/oringmaryho/business/userservice/presentation/UserController.java
Labels: ✏ feat

#105 [Company] : 업체 조회 기능 구현(일반, FeignClient)
  common/build.gradle
  company-service/build.gradle
  company-service/src/main/java/com/oingmaryho/business/companyservice/application/CompanyService.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/application/dto/mapper/CompanyApplicationMapper.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/application/dto/request/CompanySearchRequestServiceDto.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/application/service/CompanyFeignService.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/application/service/CompanyService.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/domain/Company.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/domain/CompanySearchCriteria.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/domain/repository/CompanyRepository.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/domain/repository/CompanyRepositoryImpl.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/infrastructure/CompanyJpaRepository.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/infrastructure/CompanyQueryDslRepository.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/infrastructure/CompanyQueryDslRepositoryImpl.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/presentation/controller/CompanyController.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/presentation/controller/CompanyFeignClientController.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/presentation/dto/mapper/CompanyPresentationMapper.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/presentation/dto/request/CompanySearchRequestDto.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/utils/PageableUtils.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/utils/QueryDslUtils.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/utils/SortConstants.java
Labels: ✏ feat

#108 [Company] : 업체 생성 기능 구현
  company-service/src/main/java/com/oingmaryho/business/companyservice/application/dto/mapper/CompanyApplicationMapper.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/application/service/CompanyService.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/domain/repository/CompanyRepository.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/domain/repository/CompanyRepositoryImpl.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/infrastructure/CompanyJpaRepository.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/presentation/controller/CompanyController.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/presentation/dto/mapper/CompanyPresentationMapper.java
Labels: ✏ feat

#109 [Hub] : 허브 수정 기능 구현
  hub-service/src/main/java/com/oingmaryho/business/hubservice/application/HubAdminService.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/application/HubService.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/application/dto/request/HubUpdateRequestServiceDto.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/application/dto/response/HubUpdateResponseServiceDto.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/domain/Hub.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/domain/repository/HubRepository.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/presentation/HubAdminController.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/presentation/dto/mapper/HubPresentationMapper.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/presentation/dto/request/HubUpdateRequestDto.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/presentation/dto/response/HubUpdateResponseDto.java
  hub-service/src/test/java/com/oingmaryho/business/hubservice/application/HubAdminServiceTest.java
Labels: ✏ feat, 📑 test

#110 [Hub] : 허브 삭제 기능 구현
  hub-service/src/main/java/com/oingmaryho/business/hubservice/application/HubAdminService.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/application/dto/request/HubDeleteRequestServiceDto.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/domain/Hub.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/presentation/HubAdminController.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/presentation/dto/mapper/HubPresentationMapper.java
  hub-service/src/test/java/com/oingmaryho/business/hubservice/application/HubAdminServiceTest.java
Labels: ✏ feat, 📑 test

#112 [Company] : 업체 수정 기능 구현
  company-service/src/main/java/com/oingmaryho/business/companyservice/application/dto/mapper/CompanyApplicationMapper.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/application/dto/request/CompanyUpdateRequestServiceDto.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/application/service/CompanyService.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/domain/Company.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/domain/repository/CompanyRepositoryImpl.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/presentation/controller/CompanyController.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/presentation/dto/mapper/CompanyPresentationMapper.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/presentation/dto/request/CompanyUpdateRequestDto.java
  company-service/src/test/java/com/oingmaryho/business/companyservice/application/service/CompanyServiceTest.java
Labels: ✏ feat

#114 [User] : 로그인 시 저장되는 정보 변경
  user-service/src/main/java/com/oringmaryho/business/userservice/application/UserService.java
Labels: 🛠 fix

#116 [Order] : 주문 조회 기능 수정(마스터) #115
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/dto/mapper/OrderApplicationMapper.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/dto/request/OrderTotalPriceUpdateRequestServiceDto.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/service/OrderAdminService.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/domain/Order.java
Labels: 🛠 fix

#117 [User] : 슬랙 인증 기능 추가#67
  gateway-service/src/main/java/com/oingmaryho/infrastructure/gateway_service/config/RedisConfig.java
  user-service/docker-compose.yml
  user-service/src/main/java/com/oringmaryho/business/userservice/application/UserAdminService.java
  user-service/src/main/java/com/oringmaryho/business/userservice/application/UserService.java
  user-service/src/main/java/com/oringmaryho/business/userservice/application/dto/request/UserSlackCodeRequestServiceDto.java
  user-service/src/main/java/com/oringmaryho/business/userservice/application/dto/request/UserSlackConfirmRequestServiceDto.java
  user-service/src/main/java/com/oringmaryho/business/userservice/application/utils/CodeStorage.java
  user-service/src/main/java/com/oringmaryho/business/userservice/application/utils/DirectMessageAuthService.java
  user-service/src/main/java/com/oringmaryho/business/userservice/config/security/RedisConfig.java
  user-service/src/main/java/com/oringmaryho/business/userservice/domain/repository/CustomUserRepository.java
  user-service/src/main/java/com/oringmaryho/business/userservice/domain/repository/UserRepository.java
  user-service/src/main/java/com/oringmaryho/business/userservice/exception/ErrorCode.java
  user-service/src/main/java/com/oringmaryho/business/userservice/infrastructure/SlackCodeStorageImpl.java
  user-service/src/main/java/com/oringmaryho/business/userservice/infrastructure/SlackServiceImpl.java
  user-service/src/main/java/com/oringmaryho/business/userservice/infrastructure/UserJpaRepository.java
  user-service/src/main/java/com/oringmaryho/business/userservice/presentation/UserController.java
  user-service/src/main/java/com/oringmaryho/business/userservice/presentation/UserPresentationMapper.java
  user-service/src/main/java/com/oringmaryho/business/userservice/presentation/dto/request/UserSlackCodeRequestDto.java
  user-service/src/main/java/com/oringmaryho/business/userservice/presentation/dto/request/UserSlackConfirmRequestDto.java
  user-service/src/test/java/com/oringmaryho/business/userservice/application/UserAdminServiceTest.java
  user-service/src/test/java/com/oringmaryho/business/userservice/application/UserServiceTest.java
Labels: ✏ feat

#118 [Company] : 업체 삭제 기능 구현
  common/src/main/java/com/oingmaryho/business/common/entity/BaseEntity.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/application/dto/mapper/CompanyApplicationMapper.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/application/dto/request/CompanyCreateRequestServiceDto.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/application/dto/request/CompanyUpdateRequestServiceDto.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/application/dto/response/CompanyDetailsSearchResponseServiceDto.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/application/dto/response/CompanySearchResponseServiceDto.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/application/service/CompanyService.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/domain/Company.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/domain/CompanySearchCriteria.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/domain/repository/CompanyRepository.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/domain/repository/CompanyRepositoryImpl.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/domain/repository/CustomCompanyRepository.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/exception/CompanyException.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/exception/ErrorCode.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/exception/GlobalExceptionHandler.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/infrastructure/CompanyJpaRepository.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/infrastructure/CompanyQueryDslRepository.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/infrastructure/CompanyQueryDslRepositoryImpl.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/presentation/controller/CompanyController.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/presentation/dto/request/CompanyCreateRequestDto.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/presentation/dto/request/CompanyUpdateRequestDto.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/presentation/dto/response/CompanyDetailsSearchResponseDto.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/presentation/dto/response/CompanySearchResponseDto.java
  company-service/src/test/java/com/oingmaryho/business/companyservice/application/service/CompanyServiceTest.java
Labels: ✏ feat, 🛠 fix, 📑 test

#121 [User] : MASTER 사용자용 유저 권한 부여 기능 추가
  user-service/src/main/java/com/oringmaryho/business/userservice/application/UserAdminService.java
  user-service/src/main/java/com/oringmaryho/business/userservice/application/UserService.java
  user-service/src/main/java/com/oringmaryho/business/userservice/domain/User.java
  user-service/src/main/java/com/oringmaryho/business/userservice/exception/ErrorCode.java
  user-service/src/main/java/com/oringmaryho/business/userservice/presentation/UserAdminController.java
Labels: ✏ feat, ⚙ refactor

#123 [User] : 사용자 권한 수정, 삭제 기능 추가
  user-service/docker-compose.yml
  user-service/src/main/java/com/oringmaryho/business/userservice/application/UserAdminService.java
  user-service/src/main/java/com/oringmaryho/business/userservice/application/UserApplicationMapper.java
  user-service/src/main/java/com/oringmaryho/business/userservice/application/UserService.java
  user-service/src/main/java/com/oringmaryho/business/userservice/application/dto/request/UserAdminDeleteRequestServiceDto.java
  user-service/src/main/java/com/oringmaryho/business/userservice/application/dto/request/UserAdminDeleteRoleRequestServiceDto.java
  user-service/src/main/java/com/oringmaryho/business/userservice/domain/User.java
  user-service/src/main/java/com/oringmaryho/business/userservice/exception/ErrorCode.java
  user-service/src/main/java/com/oringmaryho/business/userservice/presentation/UserAdminController.java
  user-service/src/main/java/com/oringmaryho/business/userservice/presentation/UserPresentationMapper.java
  user-service/src/main/java/com/oringmaryho/business/userservice/presentation/dto/request/UserAdminDeleteRequestServiceDto.java
  user-service/src/main/java/com/oringmaryho/business/userservice/presentation/dto/request/UserAdminDeleteRoleRequestServiceDto.java
Labels: ✏ feat, ⚙ refactor

#124 [Order] : 주문 조회 기능 구현(마스터) #30
  order-service/build.gradle
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/dto/mapper/OrderApplicationMapper.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/service/OrderAdminService.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/service/OrderFeignService.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/service/OrderService.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/config/pageable/PageableConfig.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/domain/OrderSearchCriteria.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/domain/repository/CustomOrderRepository.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/domain/repository/OrderRepository.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/infrastructure/OrderJPARepository.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/infrastructure/OrderQueryRepository.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/presentation/controller/OrderAdminController.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/utils/PageableUtils.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/utils/QueryDslUtils.java
  order-service/src/test/java/com/oingmaryho/business/orderservice/application/OrderServiceTest.java
Labels: 🛠 fix

#127 [Product] : 상품 조회 기능 구현
  product-service/build.gradle
  product-service/src/main/java/com/oingmaryho/business/productservice/application/dto/request/ProductSearchRequestServiceDto.java
  product-service/src/main/java/com/oingmaryho/business/productservice/application/dto/response/ProductSearchResponseServiceDto.java
  product-service/src/main/java/com/oingmaryho/business/productservice/application/mapper/ProductApplicationMapper.java
  product-service/src/main/java/com/oingmaryho/business/productservice/application/service/ProductService.java
  product-service/src/main/java/com/oingmaryho/business/productservice/domain/ProductSearchCriteria.java
  product-service/src/main/java/com/oingmaryho/business/productservice/exception/ErrorCode.java
  product-service/src/main/java/com/oingmaryho/business/productservice/infrastructure/ProductQueryDslRepository.java
  product-service/src/main/java/com/oingmaryho/business/productservice/presentation/controller/ProductController.java
  product-service/src/main/java/com/oingmaryho/business/productservice/presentation/dto/request/ProductSearchRequestDto.java
  product-service/src/main/java/com/oingmaryho/business/productservice/presentation/dto/response/ProductSearchResponseDto.java
  product-service/src/main/java/com/oingmaryho/business/productservice/presentation/mapper/ProductPresentationMapper.java
  product-service/src/main/java/com/oingmaryho/business/productservice/utils/PageableUtils.java
  product-service/src/main/java/com/oingmaryho/business/productservice/utils/QueryDslUtils.java
  product-service/src/main/java/com/oingmaryho/business/productservice/utils/SortConstants.java
  product-service/src/test/java/com/oingmaryho/business/productservice/application/service/ProductServiceTest.java
Labels: ✏ feat

#128 [Product] : 상품 수정 기능 구현
  product-service/src/main/java/com/oingmaryho/business/productservice/application/dto/request/ProductUpdateRequestServiceDto.java
  product-service/src/main/java/com/oingmaryho/business/productservice/application/dto/response/ProductUpdateResponseServiceDto.java
  product-service/src/main/java/com/oingmaryho/business/productservice/application/mapper/ProductApplicationMapper.java
  product-service/src/main/java/com/oingmaryho/business/productservice/application/service/ProductService.java
  product-service/src/main/java/com/oingmaryho/business/productservice/domain/Product.java
  product-service/src/main/java/com/oingmaryho/business/productservice/exception/ErrorCode.java
  product-service/src/main/java/com/oingmaryho/business/productservice/presentation/controller/ProductController.java
  product-service/src/main/java/com/oingmaryho/business/productservice/presentation/dto/request/ProductUpdateRequestDto.java
  product-service/src/main/java/com/oingmaryho/business/productservice/presentation/dto/response/ProductUpdateResponseDto.java
  product-service/src/main/java/com/oingmaryho/business/productservice/presentation/mapper/ProductPresentationMapper.java
  product-service/src/test/java/com/oingmaryho/business/productservice/application/service/ProductServiceTest.java
Labels: ✏ feat, 📑 test

#129 [Hub] : 허브 이동 경로 생성(마스터) 기능 구현
  hub-service/src/main/java/com/oingmaryho/business/hubservice/application/HubAdminService.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/application/HubRouteAdminService.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/application/HubService.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/application/dto/mapper/HubRouteApplicationMapper.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/application/dto/request/HubRouteCreateRequestServiceDto.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/application/dto/response/HubRouteCreateResponseServiceDto.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/domain/Address.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/domain/HubRoute.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/domain/RouteInfo.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/domain/repository/CustomHubRepository.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/domain/repository/HubRepository.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/domain/repository/HubRouteRepository.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/domain/service/HubRouteCreateService.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/exception/ErrorCode.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/infrastructure/HubJpaRepository.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/infrastructure/HubQueryRepository.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/infrastructure/HubRepositoryImpl.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/infrastructure/HubRouteJpaRepository.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/infrastructure/HubRouteRepositoryImpl.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/presentation/HubRouteAdminController.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/presentation/dto/mapper/HubRoutePresentationMapper.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/presentation/dto/request/HubRouteCreateRequestDto.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/presentation/dto/response/HubRouteCreateResponseDto.java
  hub-service/src/test/java/com/oingmaryho/business/hubservice/application/HubRouteAdminServiceTest.java
  hub-service/src/test/java/com/oingmaryho/business/hubservice/application/HubServiceTest.java
  hub-service/src/test/java/com/oingmaryho/business/hubservice/domain/service/HubRouteCreateServiceTest.java
Labels: ✏ feat, 📑 test

#130 [Order] - 주문 수정 기능 구현 (허브 관리자)
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/service/OrderService.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/presentation/controller/OrderAdminController.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/presentation/controller/OrderController.java
Labels: ✏ feat

#131 [Product] : 상품 삭제 기능 구현
  product-service/src/main/java/com/oingmaryho/business/productservice/application/dto/request/ProductDeleteRequestServiceDto.java
  product-service/src/main/java/com/oingmaryho/business/productservice/application/service/ProductService.java
  product-service/src/main/java/com/oingmaryho/business/productservice/presentation/controller/ProductController.java
  product-service/src/main/java/com/oingmaryho/business/productservice/presentation/mapper/ProductPresentationMapper.java
Labels: ✏ feat

#133 [Order] - 주문 삭제 기능 구현(허브 관리자) #126
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/service/OrderService.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/domain/Order.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/presentation/controller/OrderController.java
Labels: ✏ feat

#135 [User] : master 사용자용 CRUD, Search 기능 구현
  user-service/build.gradle
  user-service/src/main/java/com/oringmaryho/business/userservice/application/UserAdminService.java
  user-service/src/main/java/com/oringmaryho/business/userservice/application/dto/mapper/UserApplicationMapper.java
  user-service/src/main/java/com/oringmaryho/business/userservice/application/dto/request/UserAdminCreateRequestServiceDto.java
  user-service/src/main/java/com/oringmaryho/business/userservice/application/dto/request/UserAdminSearchRequestServiceDto.java
  user-service/src/main/java/com/oringmaryho/business/userservice/application/dto/response/UserAdminFindResponseDto.java
  user-service/src/main/java/com/oringmaryho/business/userservice/application/service/UserAdminService.java
  user-service/src/main/java/com/oringmaryho/business/userservice/application/service/UserService.java
  user-service/src/main/java/com/oringmaryho/business/userservice/application/utils/CodeStorage.java
  user-service/src/main/java/com/oringmaryho/business/userservice/application/utils/RedisUtil.java
  user-service/src/main/java/com/oringmaryho/business/userservice/config/QueryDslConfig.java
  user-service/src/main/java/com/oringmaryho/business/userservice/config/cache/CacheConfig.java
  user-service/src/main/java/com/oringmaryho/business/userservice/config/cache/CacheType.java
  user-service/src/main/java/com/oringmaryho/business/userservice/config/pageable/PageableConfig.java
  user-service/src/main/java/com/oringmaryho/business/userservice/domain/User.java
  user-service/src/main/java/com/oringmaryho/business/userservice/domain/UserSearchCriteria.java
  user-service/src/main/java/com/oringmaryho/business/userservice/domain/repository/CustomUserRepository.java
  user-service/src/main/java/com/oringmaryho/business/userservice/infrastructure/RedisUtilImpl.java
  user-service/src/main/java/com/oringmaryho/business/userservice/infrastructure/UserQueryRepository.java
  user-service/src/main/java/com/oringmaryho/business/userservice/presentation/controller/UserAdminController.java
  user-service/src/main/java/com/oringmaryho/business/userservice/presentation/controller/UserController.java
  user-service/src/main/java/com/oringmaryho/business/userservice/presentation/dto/mapper/UserPresentationMapper.java
  user-service/src/main/java/com/oringmaryho/business/userservice/presentation/dto/request/UserAdminCreateRequestDto.java
  user-service/src/main/java/com/oringmaryho/business/userservice/presentation/dto/request/UserAdminSearchRequestDto.java
  user-service/src/main/java/com/oringmaryho/business/userservice/presentation/dto/response/UserAdminFindResponseDto.java
  user-service/src/main/java/com/oringmaryho/business/userservice/presentation/dto/response/UserAdminSearchResponseDto.java
  user-service/src/main/java/com/oringmaryho/business/userservice/utils/QueryDslUtils.java
  user-service/src/main/java/com/oringmaryho/business/userservice/utils/SortConstants.java
  user-service/src/test/java/com/oringmaryho/business/userservice/application/UserAdminServiceTest.java
  user-service/src/test/java/com/oringmaryho/business/userservice/application/UserServiceTest.java
Labels: ✏ feat, 🛠 fix, 📑 test, ⚙ refactor

#136 [Delivery] - 전체 로직 테스트 코드(생성 제외), criteria 반영, isDeleted 응답 분리
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/dto/mapper/DeliveryApplicationMapper.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/dto/request/DeliveryRouteSearchRequestServiceDto.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/dto/request/DeliveryRouteUpdateStatusRequestServiceDto.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/dto/request/DeliverySearchRequestServiceDto.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/dto/request/DeliveryUpdateStatusRequestServiceDto.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/dto/response/DeliveryResponseServiceDto.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/dto/response/DeliveryRouteResponseServiceDto.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/service/DeliveryAdminService.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/service/DeliveryService.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/domain/DeliveryManagerType.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/domain/DeliveryRouteSearchCriteria.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/domain/DeliverySearchCriteria.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/domain/UserRoleType.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/domain/entity/BaseEntity.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/domain/entity/Delivery.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/domain/entity/DeliveryManager.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/domain/entity/DeliveryRoute.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/domain/type/DeliveryManagerType.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/domain/type/DeliveryRouteStatus.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/domain/type/DeliveryStatus.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/domain/type/UserConfirmStatus.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/domain/type/UserRoleType.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/infrastructure/interceptor/AdminCheckInterceptor.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/infrastructure/interceptor/UserCheckInterceptor.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/infrastructure/repository/DeliveryCustomRepository.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/infrastructure/repository/DeliveryCustomRepositoryImpl.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/infrastructure/repository/DeliveryRepository.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/presentation/DeliveryAdminController.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/presentation/DeliveryController.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/presentation/dto/mapper/DeliveryPresentationMapper.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/presentation/dto/request/DeliveryRouteSearchRequestDto.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/presentation/dto/request/DeliveryRouteUpdateStatusRequestDto.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/presentation/dto/request/DeliverySearchRequestDto.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/presentation/dto/request/DeliveryUpdateStatusRequestDto.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/presentation/dto/response/DeliveryAdminResponseDto.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/presentation/dto/response/DeliveryResponseDto.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/presentation/dto/response/DeliveryRouteAdminResponseDto.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/presentation/dto/response/DeliveryRouteResponseDto.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/utils/QueryDslUtils.java
  delivery-service/src/test/java/com/oingmaryho/business/delivery_service/application/DeliveryServiceTest.java
Labels: 🐞 bug, 📑 test, ⚙ refactor

#140 [Hub] : 허브 이동 경로 조회, 수정, 삭제 기능 구현
  hub-service/src/main/java/com/oingmaryho/business/hubservice/application/HubAdminService.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/application/HubRouteAdminService.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/application/HubService.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/application/dto/mapper/HubRouteApplicationMapper.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/application/dto/request/HubRouteDeleteRequestServiceDto.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/application/dto/request/HubRouteSearchAdminRequestServiceDto.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/application/dto/request/HubRouteUpdateRequestServiceDto.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/application/dto/request/HubRoutesSearchAdminRequestServiceDto.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/application/dto/response/HubRouteSearchAdminResponseServiceDto.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/application/dto/response/HubRouteUpdateResponseServiceDto.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/domain/HubRoute.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/domain/HubRouteSearchCriteria.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/domain/repository/HubRouteRepository.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/domain/service/HubRouteCreateService.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/exception/ErrorCode.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/infrastructure/HubRouteQueryRepository.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/infrastructure/HubRouteRepositoryImpl.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/presentation/HubRouteAdminController.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/presentation/dto/mapper/HubRoutePresentationMapper.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/presentation/dto/request/HubRouteSearchAdminRequestDto.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/presentation/dto/request/HubRouteUpdateRequestDto.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/presentation/dto/response/HubRouteSearchAdminResponseDto.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/presentation/dto/response/HubRouteUpdateResponseDto.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/utils/QueryDslUtils.java
  hub-service/src/test/java/com/oingmaryho/business/hubservice/application/HubRouteAdminServiceTest.java
  hub-service/src/test/java/com/oingmaryho/business/hubservice/application/HubServiceTest.java
  hub-service/src/test/java/com/oingmaryho/business/hubservice/domain/service/HubRouteCreateServiceTest.java
Labels: ✏ feat, 📑 test

#141 [Order]: interceptor 구현 #137
  order-service/build.gradle
  order-service/src/main/java/com/oingmaryho/business/orderservice/config/Auditing.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/domain/Order.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/domain/UserRole.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/domain/UserStatus.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/infrastructure/interceptor/AdminInterceptor.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/infrastructure/interceptor/UserInterceptor.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/presentation/webconfig/WebConfig.java
Labels: ✏ feat

#144 [Order] : interceptor 코드 수정
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/dto/mapper/OrderApplicationMapper.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/config/RedisConfig.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/infrastructure/interceptor/AdminInterceptor.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/infrastructure/interceptor/UserInterceptor.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/presentation/webconfig/WebConfig.java
Labels: 🛠 fix

#146 [Delivery] : admin, 일반 사용자 서비스 메서드별 권한 로직 작성, caching
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/dto/request/DeliveryUpdateRequestServiceDto.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/service/DeliveryAdminService.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/service/DeliveryService.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/config/interceptor/WebMvcConfig.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/domain/criteria/DeliveryRouteSearchCriteria.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/domain/criteria/DeliverySearchCriteria.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/domain/entity/Delivery.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/domain/entity/DeliveryManager.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/domain/entity/DeliveryRoute.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/exception/ErrorCode.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/infrastructure/interceptor/AdminCheckInterceptor.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/infrastructure/interceptor/UserCheckInterceptor.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/infrastructure/repository/DeliveryCustomRepository.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/infrastructure/repository/DeliveryCustomRepositoryImpl.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/presentation/controller/DeliveryAdminController.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/presentation/controller/DeliveryController.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/presentation/dto/request/DeliveryUpdateRequestDto.java
  delivery-service/src/test/java/com/oingmaryho/business/delivery_service/application/DeliveryServiceTest.java
Labels: ✏ feat, 📑 test, ⚙ refactor

#148 [product] : feign client
  company-service/src/main/java/com/oingmaryho/business/companyservice/application/service/CompanyFeignService.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/presentation/controller/CompanyFeignClientController.java
  product-service/src/main/java/com/oingmaryho/business/productservice/application/dto/request/ProductCreateRequestServiceDto.java
  product-service/src/main/java/com/oingmaryho/business/productservice/application/dto/request/ProductSearchRequestServiceDto.java
  product-service/src/main/java/com/oingmaryho/business/productservice/application/dto/request/ProductUpdateRequestServiceDto.java
  product-service/src/main/java/com/oingmaryho/business/productservice/application/dto/response/ProductDetailsSearchResponseServiceDto.java
  product-service/src/main/java/com/oingmaryho/business/productservice/application/dto/response/ProductSearchResponseServiceDto.java
  product-service/src/main/java/com/oingmaryho/business/productservice/application/service/ProductFeignClientService.java
  product-service/src/main/java/com/oingmaryho/business/productservice/application/service/ProductService.java
  product-service/src/main/java/com/oingmaryho/business/productservice/domain/Product.java
  product-service/src/main/java/com/oingmaryho/business/productservice/domain/ProductSearchCriteria.java
  product-service/src/main/java/com/oingmaryho/business/productservice/exception/ErrorCode.java
  product-service/src/main/java/com/oingmaryho/business/productservice/infrastructure/ProductQueryDslRepository.java
  product-service/src/main/java/com/oingmaryho/business/productservice/presentation/controller/ProductController.java
  product-service/src/main/java/com/oingmaryho/business/productservice/presentation/controller/ProductFeignClientController.java
  product-service/src/main/java/com/oingmaryho/business/productservice/presentation/dto/request/ProductCreateRequestDto.java
  product-service/src/main/java/com/oingmaryho/business/productservice/presentation/dto/request/ProductSearchRequestDto.java
  product-service/src/main/java/com/oingmaryho/business/productservice/presentation/dto/request/ProductUpdateRequestDto.java
  product-service/src/main/java/com/oingmaryho/business/productservice/presentation/dto/response/ProductDetailsSearchResponseDto.java
  product-service/src/main/java/com/oingmaryho/business/productservice/presentation/dto/response/ProductSearchResponseDto.java
  product-service/src/test/java/com/oingmaryho/business/productservice/application/service/ProductServiceTest.java
Labels: ✏ feat

#151 [product] : 주문과 RabbitMQ 연결
  product-service/src/main/java/com/oingmaryho/business/productservice/application/dto/request/ProductCreateRequestServiceDto.java
  product-service/src/main/java/com/oingmaryho/business/productservice/application/dto/request/ProductQueueFailedRequestDto.java
  product-service/src/main/java/com/oingmaryho/business/productservice/application/dto/request/ProductQueueRequestDto.java
  product-service/src/main/java/com/oingmaryho/business/productservice/application/dto/request/ProductSearchRequestServiceDto.java
  product-service/src/main/java/com/oingmaryho/business/productservice/application/dto/request/ProductUpdateRequestServiceDto.java
  product-service/src/main/java/com/oingmaryho/business/productservice/application/dto/response/ProductDetailsSearchResponseServiceDto.java
  product-service/src/main/java/com/oingmaryho/business/productservice/application/dto/response/ProductQueueResponseDto.java
  product-service/src/main/java/com/oingmaryho/business/productservice/application/dto/response/ProductSearchResponseServiceDto.java
  product-service/src/main/java/com/oingmaryho/business/productservice/config/rabbitMQ/RabbitMQConfig.java
  product-service/src/main/java/com/oingmaryho/business/productservice/domain/Product.java
  product-service/src/main/java/com/oingmaryho/business/productservice/domain/ProductSearchCriteria.java
  product-service/src/main/java/com/oingmaryho/business/productservice/exception/ErrorCode.java
  product-service/src/main/java/com/oingmaryho/business/productservice/infrastructure/ProductQueryDslRepository.java
  product-service/src/main/java/com/oingmaryho/business/productservice/infrastructure/messaging/ProductCompensationListener.java
  product-service/src/main/java/com/oingmaryho/business/productservice/infrastructure/messaging/ProductOrderListener.java
  product-service/src/main/java/com/oingmaryho/business/productservice/presentation/controller/ProductController.java
  product-service/src/main/java/com/oingmaryho/business/productservice/presentation/dto/request/ProductCreateRequestDto.java
  product-service/src/main/java/com/oingmaryho/business/productservice/presentation/dto/request/ProductSearchRequestDto.java
  product-service/src/main/java/com/oingmaryho/business/productservice/presentation/dto/request/ProductUpdateRequestDto.java
  product-service/src/main/java/com/oingmaryho/business/productservice/presentation/dto/response/ProductSearchResponseDto.java
Labels: ✏ feat, 🛠 fix

#152 [Order] - 주문 생성 기능 구현 #29
  order-service/build.gradle
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/dto/mapper/OrderApplicationMapper.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/dto/request/OrderCreateRequestServiceDto.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/dto/request/OrderDetailCreateRequestServiceDto.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/dto/request/ProductQueueRequestDto.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/dto/response/ProductQueueResponseDto.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/service/OrderAdminService.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/service/OrderService.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/service/feignclient/CompanyClient.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/service/feignclient/ProductClient.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/config/OrderApplicationQueueConfig.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/domain/Order.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/domain/OrderDetail.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/exception/ErrorCode.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/infrastructure/OrderQueryRepository.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/presentation/controller/OrderAdminController.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/presentation/dto/mapper/OrderPresentationMapper.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/presentation/dto/request/OrderCreateRequestDto.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/presentation/dto/request/OrderDetailCreateRequestDto.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/presentation/dto/response/CompanyDetailsSearchResponseDto.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/presentation/dto/response/ProductDetailsSearchResponseDto.java
Labels: ✏ feat, ⚙ refactor

#153 [Hub] : 허브 경로 Map API 연결 및 경로 생성 로직 skeleton code 구현
  hub-service/build.gradle
  hub-service/src/main/java/com/oingmaryho/business/hubservice/application/HubAdminService.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/application/HubRouteService.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/application/dto/mapper/HubApplicationMapper.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/application/dto/request/HubCreateRequestServiceDto.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/application/dto/request/HubPathRequestServiceDto.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/application/dto/response/HubRouteSearchResponseServiceDto.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/domain/repository/HubRepository.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/domain/repository/HubRouteRepository.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/domain/service/GeoSpatialService.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/domain/service/HubCreateService.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/domain/service/HubPathService.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/domain/service/HubRouteInitService.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/domain/service/ShortestPathService.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/infrastructure/DijkstraServiceImpl.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/infrastructure/DirectionsResponse.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/infrastructure/GeocodingResponse.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/infrastructure/HubQueryRepository.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/infrastructure/HubRepositoryImpl.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/infrastructure/HubRouteJpaRepository.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/infrastructure/HubRouteRepositoryImpl.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/infrastructure/NaverMapApiService.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/presentation/HubFeignClientController.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/presentation/dto/request/HubCreateRequestDto.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/presentation/dto/request/HubPathRequestDto.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/presentation/dto/response/HubRouteSearchResponseDto.java
  hub-service/src/test/java/com/oingmaryho/business/hubservice/application/HubAdminServiceTest.java
Labels: ✏ feat

#156 [Hub] : 허브 이동 경로를 위한 FeignClient
  hub-service/src/main/java/com/oingmaryho/business/hubservice/application/HubRouteService.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/application/HubService.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/application/dto/request/HubPathRequestServiceDto.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/domain/repository/HubRepository.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/domain/service/HubInfoService.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/infrastructure/HubJpaRepository.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/infrastructure/HubRepositoryImpl.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/presentation/HubFeignClientController.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/presentation/dto/mapper/HubPresentationMapper.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/presentation/dto/request/HubPathRequestDto.java
Labels: ✏ feat

#157 [Hub] : 허브 이동경로 최적화 알고리즘 추가
  hub-service/src/main/java/com/oingmaryho/business/hubservice/domain/service/HubPathService.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/domain/service/ShortestPathService.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/infrastructure/DijkstraServiceImpl.java
Labels: ✏ feat

#158 [Order] - 주문 생성 기능 구현 #29
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/service/OrderAdminService.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/config/OrderApplicationQueueConfig.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/domain/Order.java
Labels: ✏ feat, 🛠 fix

#159 [User] : user id를 받아 role을 반환하는feign api추가
  user-service/src/main/java/com/oringmaryho/business/userservice/application/service/UserFeignService.java
  user-service/src/main/java/com/oringmaryho/business/userservice/presentation/controller/UserFeignClientController.java
  user-service/src/main/java/com/oringmaryho/business/userservice/presentation/dto/mapper/UserPresentationMapper.java
  user-service/src/main/java/com/oringmaryho/business/userservice/presentation/dto/request/UserFromDeliveryGetRoleRequestServiceDto.java
Labels: ✏ feat

#161 [Delivery] : FeignClient 로직까지 적용해 권한별 유효성 검증 및 로직 전환
  company-service/src/main/java/com/oingmaryho/business/companyservice/presentation/controller/CompanyFeignClientController.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/DeliveryServiceApplication.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/dto/request/DeliveryCreationRequestServiceDto.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/dto/request/DeliveryRouteSearchRequestServiceDto.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/dto/request/DeliveryRouteUpdateStatusRequestServiceDto.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/dto/request/DeliverySearchRequestServiceDto.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/dto/request/DeliveryUpdateRequestServiceDto.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/dto/request/DeliveryUpdateStatusRequestServiceDto.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/dto/response/DeliveryResponseServiceDto.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/dto/response/DeliveryRouteResponseServiceDto.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/feign/CompanyClient.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/feign/CompanyDetailsSearchRequestServiceDto.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/feign/CompanyDetailsSearchResponseDto.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/feign/HubClient.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/feign/HubPathResponseDto.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/feign/HubSearchResponseDto.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/feign/UserClient.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/service/DeliveryAdminService.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/service/DeliveryService.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/config/cache/CacheType.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/config/redis/RedisConfig.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/domain/criteria/DeliveryRouteSearchCriteria.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/domain/criteria/DeliverySearchCriteria.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/domain/entity/Delivery.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/domain/entity/DeliveryRoute.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/exception/ErrorCode.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/infrastructure/interceptor/AdminCheckInterceptor.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/infrastructure/interceptor/UserCheckInterceptor.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/infrastructure/repository/DeliveryCustomRepository.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/infrastructure/repository/DeliveryCustomRepositoryImpl.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/infrastructure/repository/DeliveryManagerRepository.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/presentation/controller/DeliveryAdminController.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/presentation/controller/DeliveryController.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/presentation/dto/mapper/DeliveryPresentationMapper.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/presentation/dto/request/DeliveryCreationRequestDto.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/presentation/dto/request/DeliveryRouteSearchRequestDto.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/presentation/dto/request/DeliverySearchRequestDto.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/presentation/dto/request/DeliveryUpdateRequestDto.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/presentation/dto/response/DeliveryAdminResponseDto.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/presentation/dto/response/DeliveryResponseDto.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/presentation/dto/response/DeliveryRouteAdminResponseDto.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/presentation/dto/response/DeliveryRouteResponseDto.java
  delivery-service/src/test/java/com/oingmaryho/business/delivery_service/application/DeliveryServiceTest.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/application/dto/response/HubRouteSearchAdminResponseServiceDto.java
Labels: ✏ feat, 📑 test

#164 [Product] : product 메시지 큐 설정
  product-service/src/main/java/com/oingmaryho/business/productservice/config/rabbitMQ/RabbitMQConfig.java
  product-service/src/main/java/com/oingmaryho/business/productservice/infrastructure/messaging/ProductCompensationListener.java
  product-service/src/main/java/com/oingmaryho/business/productservice/infrastructure/messaging/ProductOrderListener.java
Labels: ✏ feat

#165 [Order] : 주문 생성 기능 구현 #29
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/event/OrderEvent.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/service/OrderAdminService.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/domain/Order.java
Labels: ✏ feat

#166 [Hub] : 허브 이동 경로 로직 수정 및 FeignClient 응답값 설정
  hub-service/src/main/java/com/oingmaryho/business/hubservice/application/HubAdminService.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/application/HubRouteAdminService.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/application/HubRouteService.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/application/dto/mapper/HubRouteApplicationMapper.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/application/dto/request/HubRouteCreateRequestServiceDto.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/domain/service/HubRouteCreateService.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/domain/service/HubRouteInitService.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/infrastructure/DijkstraServiceImpl.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/presentation/HubFeignClientController.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/presentation/dto/mapper/HubPresentationMapper.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/presentation/dto/mapper/HubRoutePresentationMapper.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/presentation/dto/request/HubRouteCreateRequestDto.java
  hub-service/src/test/java/com/oingmaryho/business/hubservice/application/HubAdminServiceTest.java
  hub-service/src/test/java/com/oingmaryho/business/hubservice/application/HubRouteAdminServiceTest.java
  hub-service/src/test/java/com/oingmaryho/business/hubservice/domain/service/HubRouteCreateServiceTest.java
Labels: ✏ feat

#170 [Slack] : 슬랙 프로젝트 생성
  build.gradle
  settings.gradle
  slack-service/.gitattributes
  slack-service/HELP.md
  slack-service/build.gradle
  slack-service/gradle/wrapper/gradle-wrapper.jar
  slack-service/gradle/wrapper/gradle-wrapper.properties
  slack-service/settings.gradle
  slack-service/src/main/java/com/oringmaryho/business/slackservice/SlackServiceApplication.java
  slack-service/src/main/java/com/oringmaryho/business/slackservice/application/dto/mapper/SlackApplicationMapper.java
  slack-service/src/main/java/com/oringmaryho/business/slackservice/application/dto/request/SlackMessageCreateRequestServiceDto.java
  slack-service/src/main/java/com/oringmaryho/business/slackservice/application/dto/request/SlackMessageDeleteRequestServiceDto.java
  slack-service/src/main/java/com/oringmaryho/business/slackservice/application/dto/request/SlackMessageFindRequestServiceDto.java
  slack-service/src/main/java/com/oringmaryho/business/slackservice/application/dto/request/SlackMessageSearchRequestServiceDto.java
  slack-service/src/main/java/com/oringmaryho/business/slackservice/application/dto/request/SlackMessageUpdateRequestServiceDto.java
  slack-service/src/main/java/com/oringmaryho/business/slackservice/application/service/SlackMessageService.java
  slack-service/src/main/java/com/oringmaryho/business/slackservice/application/utils/RedisUtil.java
  slack-service/src/main/java/com/oringmaryho/business/slackservice/config/JpaAuditingConfig.java
  slack-service/src/main/java/com/oringmaryho/business/slackservice/config/QueryDslConfig.java
  slack-service/src/main/java/com/oringmaryho/business/slackservice/config/cache/CacheConfig.java
  slack-service/src/main/java/com/oringmaryho/business/slackservice/config/cache/CacheType.java
  slack-service/src/main/java/com/oringmaryho/business/slackservice/config/interceptor/WebMvcConfig.java
  slack-service/src/main/java/com/oringmaryho/business/slackservice/config/pageable/PageableConfig.java
  slack-service/src/main/java/com/oringmaryho/business/slackservice/config/security/RedisConfig.java
  slack-service/src/main/java/com/oringmaryho/business/slackservice/domain/SlackMessage.java
  slack-service/src/main/java/com/oringmaryho/business/slackservice/domain/SlackMessageSearchCriteria.java
  slack-service/src/main/java/com/oringmaryho/business/slackservice/exception/ErrorCode.java
  slack-service/src/main/java/com/oringmaryho/business/slackservice/exception/GlobalExceptionHandler.java
  slack-service/src/main/java/com/oringmaryho/business/slackservice/exception/SlackException.java
  slack-service/src/main/java/com/oringmaryho/business/slackservice/infrastructure/RedisUtilImpl.java
  slack-service/src/main/java/com/oringmaryho/business/slackservice/infrastructure/SlackJpaRepository.java
  slack-service/src/main/java/com/oringmaryho/business/slackservice/infrastructure/interceptor/AdminCheckInterceptor.java
  slack-service/src/main/java/com/oringmaryho/business/slackservice/infrastructure/interceptor/UserCheckInterceptor.java
  slack-service/src/main/java/com/oringmaryho/business/slackservice/presentation/controller/SlackAdminController.java
  slack-service/src/main/java/com/oringmaryho/business/slackservice/presentation/dto/mapper/SlackPresentationMapper.java
  slack-service/src/main/java/com/oringmaryho/business/slackservice/presentation/dto/request/SlackMessageCreateRequestDto.java
  slack-service/src/main/java/com/oringmaryho/business/slackservice/presentation/dto/request/SlackMessageRequestDto.java
  slack-service/src/main/java/com/oringmaryho/business/slackservice/presentation/dto/request/SlackMessageSearchRequestDto.java
  slack-service/src/main/java/com/oringmaryho/business/slackservice/presentation/dto/request/SlackMessageUpdateResponseDto.java
  slack-service/src/main/java/com/oringmaryho/business/slackservice/presentation/dto/response/SlackMessageResponseDto.java
  slack-service/src/main/java/com/oringmaryho/business/slackservice/utils/QueryDslUtils.java
  slack-service/src/main/java/com/oringmaryho/business/slackservice/utils/SortConstants.java
  slack-service/src/main/resources/application.yml
  slack-service/src/test/java/com/oringmaryho/business/slackservice/SlackServiceApplicationTests.java
  user-service/build.gradle
  user-service/src/main/java/com/oringmaryho/business/userservice/presentation/controller/UserFeignClientController.java
Labels: ✏ feat

#173 [Delivery] message queue + 배송 생성
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/dto/mapper/DeliveryApplicationMapper.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/dto/request/DeliveryCreationRequestServiceDto.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/dto/request/DeliveryRouteSearchRequestServiceDto.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/dto/request/DeliverySearchRequestServiceDto.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/dto/response/DeliveryCreationResponseServiceDto.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/dto/response/DeliveryResponseServiceDto.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/feign/CompanyClient.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/feign/HubClient.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/feign/UserClient.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/messaging/DeliveryOrderListener.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/service/DeliveryAdminService.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/service/DeliveryService.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/config/interceptor/WebMvcConfig.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/config/rabbitmq/RabbitMQConfig.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/domain/criteria/DeliveryRouteSearchCriteria.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/domain/criteria/DeliverySearchCriteria.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/domain/entity/BaseEntity.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/domain/entity/Delivery.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/domain/entity/DeliveryManager.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/infrastructure/repository/DeliveryCustomRepository.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/infrastructure/repository/DeliveryCustomRepositoryImpl.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/infrastructure/repository/DeliveryManagerRepository.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/presentation/controller/DeliveryAdminController.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/presentation/controller/DeliveryController.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/presentation/dto/mapper/DeliveryPresentationMapper.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/presentation/dto/request/DeliveryCreationRequestDto.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/presentation/dto/request/DeliveryRouteSearchRequestDto.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/presentation/dto/request/DeliverySearchRequestDto.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/presentation/dto/response/DeliveryCreationResponseDto.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/presentation/dto/response/DeliveryResponseDto.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/presentation/interceptor/AdminCheckInterceptor.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/presentation/interceptor/UserCheckInterceptor.java
  delivery-service/src/test/java/com/oingmaryho/business/delivery_service/application/DeliveryServiceTest.java
Labels: ✏ feat, 🛠 fix

#175 [common] : 권한 체크 어노테이션 구성
  common/build.gradle
  common/src/main/java/com/oingmaryho/business/common/domain/entity/BaseEntity.java
  common/src/main/java/com/oingmaryho/business/common/domain/type/UserConfirmStatus.java
  common/src/main/java/com/oingmaryho/business/common/domain/type/UserRoleType.java
  common/src/main/java/com/oingmaryho/business/common/exception/BaseErrorCode.java
  common/src/main/java/com/oingmaryho/business/common/exception/BaseException.java
  common/src/main/java/com/oingmaryho/business/common/exception/CommonErrorCode.java
  common/src/main/java/com/oingmaryho/business/common/exception/GlobalExceptionHandler.java
  common/src/main/java/com/oingmaryho/business/common/infrastructure/annotation/RequiredRoles.java
  common/src/main/java/com/oingmaryho/business/common/presentation/interceptor/AdminCheckInterceptor.java
  common/src/main/java/com/oingmaryho/business/common/presentation/interceptor/UserCheckInterceptor.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/domain/Company.java
  product-service/src/main/java/com/oingmaryho/business/productservice/config/interceptor/WebMvcConfig.java
  product-service/src/main/java/com/oingmaryho/business/productservice/config/redis/RedisConfig.java
  product-service/src/main/java/com/oingmaryho/business/productservice/domain/Product.java
  product-service/src/main/java/com/oingmaryho/business/productservice/presentation/controller/ProductController.java
Labels: ✏ feat, 🛠 fix

#176 [company] : 권한별 로직 처리
  common/src/main/java/com/oingmaryho/business/common/presentation/interceptor/AdminCheckInterceptor.java
  common/src/main/java/com/oingmaryho/business/common/presentation/interceptor/UserCheckInterceptor.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/application/service/CompanyService.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/application/service/feignClient/HubClient.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/config/interceptor/WebMvcConfig.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/config/redis/RedisConfig.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/domain/repository/CompanyRepository.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/exception/ErrorCode.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/presentation/controller/CompanyController.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/presentation/controller/CompanyFeignClientController.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/presentation/dto/response/HubSearchResponseDto.java
  company-service/src/test/java/com/oingmaryho/business/companyservice/application/service/CompanyServiceTest.java
Labels: ✏ feat, 🛠 fix

#179 [Order] - 배송 메시지 큐 연동 #168
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/dto/mapper/OrderApplicationMapper.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/dto/request/DeliveryCreationRequestDto.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/dto/request/OrderCreateRequestServiceDto.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/dto/response/DeliveryCreationResponseDto.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/event/OrderEvent.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/event/OrderEventHandler.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/service/OrderAdminService.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/service/feignclient/CompanyClient.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/service/queue/OrderQueue.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/config/OrderApplicationQueueConfig.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/config/RedisConfig.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/domain/Order.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/domain/OrderDetail.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/infrastructure/interceptor/AdminInterceptor.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/infrastructure/interceptor/UserInterceptor.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/presentation/controller/OrderAdminController.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/presentation/dto/mapper/OrderPresentationMapper.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/presentation/webconfig/WebConfig.java
Labels: ✏ feat, 🛠 fix, ⚙ refactor

#180 [Slack] : slack service read, search 기능 추가
  slack-service/src/main/java/com/oringmaryho/business/slackservice/application/dto/mapper/SlackApplicationMapper.java
  slack-service/src/main/java/com/oringmaryho/business/slackservice/application/dto/request/SlackMessageSearchRequestServiceDto.java
  slack-service/src/main/java/com/oringmaryho/business/slackservice/application/service/SlackAdminMessageService.java
  slack-service/src/main/java/com/oringmaryho/business/slackservice/domain/SlackMessage.java
  slack-service/src/main/java/com/oringmaryho/business/slackservice/domain/SlackMessageSearchCriteria.java
  slack-service/src/main/java/com/oringmaryho/business/slackservice/domain/repository/CustomSlackMessageRepository.java
  slack-service/src/main/java/com/oringmaryho/business/slackservice/infrastructure/SlackMessageQueryRepository.java
  slack-service/src/main/java/com/oringmaryho/business/slackservice/presentation/controller/SlackAdminController.java
  slack-service/src/main/java/com/oringmaryho/business/slackservice/presentation/dto/mapper/SlackPresentationMapper.java
  slack-service/src/main/java/com/oringmaryho/business/slackservice/presentation/dto/request/SlackMessageSearchRequestDto.java
  slack-service/src/main/java/com/oringmaryho/business/slackservice/presentation/dto/response/SlackMessageResponseDto.java
  slack-service/src/main/java/com/oringmaryho/business/slackservice/utils/QueryDslUtils.java
  user-service/src/main/java/com/oringmaryho/business/userservice/application/service/UserAdminService.java
Labels: ✏ feat

#181 [company] : 권한별 로직 처리
  company-service/src/main/java/com/oingmaryho/business/companyservice/application/service/CompanyService.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/application/service/feignClient/HubClient.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/config/JpaAuditingConfig.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/config/audit/JpaAuditingConfig.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/config/interceptor/WebMvcConfig.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/exception/ErrorCode.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/presentation/controller/CompanyController.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/presentation/dto/request/CompanyUpdateRequestDto.java
  company-service/src/test/java/com/oingmaryho/business/companyservice/application/service/CompanyServiceTest.java
  product-service/src/main/java/com/oingmaryho/business/productservice/config/audit/JpaAuditingConfig.java
  product-service/src/main/java/com/oingmaryho/business/productservice/config/interceptor/WebMvcConfig.java
Labels: ✏ feat, 🛠 fix

#186 [common] : interceptor exception handler 적용
  common/src/main/java/com/oingmaryho/business/common/exception/CommonErrorCode.java
  common/src/main/java/com/oingmaryho/business/common/presentation/interceptor/AdminCheckInterceptor.java
  common/src/main/java/com/oingmaryho/business/common/presentation/interceptor/UserCheckInterceptor.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/config/cache/CacheConfig.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/config/cache/CacheType.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/config/interceptor/WebMvcConfig.java
Labels: 🛠 fix

#187 [Hub] : 허브 권한 관리 기능 및 Auditing 추가
  hub-service/src/main/java/com/oingmaryho/business/hubservice/application/HubAdminService.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/application/HubRouteAdminService.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/application/HubRouteService.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/application/dto/request/HubRouteSearchRequestServiceDto.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/application/dto/request/HubRoutesSearchRequestServiceDto.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/application/dto/response/HubRouteSearchResponseServiceDto.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/config/JpaAuditingConfig.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/config/RedisConfig.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/config/WebMvcConfig.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/config/cache/CacheType.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/domain/BaseEntity.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/domain/Hub.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/domain/HubRoute.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/domain/repository/HubRouteRepository.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/domain/service/HubRouteDeleteService.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/infrastructure/HubQueryRepository.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/infrastructure/HubRouteJpaRepository.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/infrastructure/HubRouteQueryRepository.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/infrastructure/HubRouteRepositoryImpl.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/presentation/HubAdminController.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/presentation/HubRouteAdminController.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/presentation/HubRouteController.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/presentation/dto/mapper/HubRoutePresentationMapper.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/presentation/dto/request/HubRouteSearchRequestDto.java
  hub-service/src/main/java/com/oingmaryho/business/hubservice/presentation/dto/response/HubRouteSearchResponseDto.java
  hub-service/src/test/java/com/oingmaryho/business/hubservice/application/HubAdminServiceTest.java
  hub-service/src/test/java/com/oingmaryho/business/hubservice/application/HubRouteAdminServiceTest.java
Labels: ✏ feat

#189 [product] : 권한별 로직 처리
  company-service/src/main/java/com/oingmaryho/business/companyservice/application/service/CompanyService.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/domain/repository/CompanyRepository.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/presentation/controller/CompanyController.java
  product-service/src/main/java/com/oingmaryho/business/productservice/application/dto/request/ProductUpdateRequestServiceDto.java
  product-service/src/main/java/com/oingmaryho/business/productservice/application/service/ProductService.java
  product-service/src/main/java/com/oingmaryho/business/productservice/application/service/feignClient/CompanyClient.java
  product-service/src/main/java/com/oingmaryho/business/productservice/application/service/feignClient/HubClient.java
  product-service/src/main/java/com/oingmaryho/business/productservice/config/cache/CacheConfig.java
  product-service/src/main/java/com/oingmaryho/business/productservice/config/cache/CacheType.java
  product-service/src/main/java/com/oingmaryho/business/productservice/domain/Product.java
  product-service/src/main/java/com/oingmaryho/business/productservice/domain/repository/ProductRepository.java
  product-service/src/main/java/com/oingmaryho/business/productservice/exception/ErrorCode.java
  product-service/src/main/java/com/oingmaryho/business/productservice/presentation/controller/ProductController.java
  product-service/src/main/java/com/oingmaryho/business/productservice/presentation/dto/request/ProductUpdateRequestDto.java
  product-service/src/main/java/com/oingmaryho/business/productservice/presentation/dto/response/CompanyDetailsSearchResponseDto.java
  product-service/src/main/java/com/oingmaryho/business/productservice/presentation/dto/response/HubSearchResponseDto.java
  product-service/src/test/java/com/oingmaryho/business/productservice/application/service/ProductServiceTest.java
Labels: ✏ feat, 🛠 fix

#193 [Order] : 상세 주문 조회 (사용자) #185
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/dto/response/HubSearchResponseDto.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/service/OrderService.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/service/feignclient/HubClient.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/domain/Order.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/domain/repository/OrderRepository.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/exception/ErrorCode.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/infrastructure/interceptor/AdminInterceptor.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/presentation/controller/OrderController.java
Labels: ✏ feat

#195 [Hub] : 허브 정보 조회 FeignClient
  hub-service/src/main/java/com/oingmaryho/business/hubservice/presentation/HubFeignClientController.java
Labels: ✏ feat

#199 [Slack] : mq 설정 파일 및 큐 이름 수정
  slack-service/src/main/java/com/oringmaryho/business/slackservice/config/messaging/RabbitMQConfig.java
  slack-service/src/main/java/com/oringmaryho/business/slackservice/infrastructure/SlackMessageListener.java
  user-service/src/main/java/com/oringmaryho/business/userservice/application/service/UserAdminService.java
  user-service/src/main/java/com/oringmaryho/business/userservice/config/messaging/RabbitMQConfig.java
  user-service/src/main/java/com/oringmaryho/business/userservice/infrastructure/RabbitMQMessagePublisher.java
Labels: 🛠 fix, ⚙ refactor

#202 [User] : user id로 username 받는 feign api 추가
  user-service/src/main/java/com/oringmaryho/business/userservice/application/service/UserFeignService.java
  user-service/src/main/java/com/oringmaryho/business/userservice/presentation/controller/UserFeignClientController.java
Labels: ✏ feat

#204 [User] : 유저 삭제 시 redis 삭제 로직 추가
  user-service/src/main/java/com/oringmaryho/business/userservice/application/service/UserAdminService.java
  user-service/src/main/java/com/oringmaryho/business/userservice/application/service/UserService.java
  user-service/src/main/java/com/oringmaryho/business/userservice/infrastructure/RabbitMQMessagePublisher.java
Labels: ✏ feat

#208 [Product] : rabbitMQ 요청 dto 변경
  product-service/src/main/java/com/oingmaryho/business/productservice/application/messaging/ProductCompensationListener.java
  product-service/src/main/java/com/oingmaryho/business/productservice/application/messaging/ProductOrderListener.java
  product-service/src/main/java/com/oingmaryho/business/productservice/config/rabbitMQ/RabbitMQConfig.java
Labels: 🐞 bug

#209 [Delivery] : Response 수정, 로직 변경
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/dto/mapper/DeliveryApplicationMapper.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/dto/response/DeliveryCreationResponseServiceDto.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/dto/response/HubPathResponseDto.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/event/DeliveryCreationEventHandler.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/feign/UserClient.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/service/DeliveryAdminService.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/exception/ErrorCode.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/infrastructure/fallback/UserClientFallback.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/presentation/dto/response/DeliveryCreationResponseDto.java
Labels: ✏ feat

#210 [Order] - 전체 주문 조회 기능 수정하기 #184
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/service/OrderService.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/domain/Order.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/domain/repository/CustomOrderRepository.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/infrastructure/OrderQueryRepository.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/infrastructure/interceptor/AdminInterceptor.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/infrastructure/interceptor/UserInterceptor.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/presentation/controller/OrderController.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/presentation/webconfig/WebConfig.java
Labels: 🛠 fix, ⚙ refactor

#212 [Delivery] : 주문 - 배송 - 주문 - 슬랙 연동
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/dto/mapper/DeliveryApplicationMapper.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/dto/response/DeliveryCreationResponseServiceDto.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/event/DeliveryCreationEventHandler.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/feign/UserClient.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/service/DeliveryAdminService.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/presentation/dto/response/DeliveryCreationResponseDto.java
  user-service/src/main/java/com/oringmaryho/business/userservice/config/interceptor/WebMvcConfig.java
Labels: ✏ feat, 🛠 fix

#215 [Slack] : queueSlack과 연결 코드 추가
  slack-service/src/main/java/com/oringmaryho/business/slackservice/config/messaging/RabbitMQConfig.java
Labels: 🛠 fix

#214 [Order] - 슬랙 메시지 연동 # 211
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/dto/request/SlackMessageDto.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/dto/response/DeliveryCreationResponseDto.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/event/OrderEventHandler.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/service/OrderAdminService.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/service/feignclient/ProductClient.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/service/queue/OrderQueue.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/config/OrderApplicationQueueConfig.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/infrastructure/OrderQueryRepository.java
Labels: ✏ feat

#219 [Delivery] : 배송 담당자 조회, 검색
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/dto/mapper/DeliveryApplicationMapper.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/dto/request/DeliveryManagerDetailRequestServiceDto.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/dto/request/DeliveryManagerSearchRequestServiceDto.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/dto/response/DeliveryManagerResponseServiceDto.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/service/DeliveryAdminService.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/service/DeliveryService.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/domain/criteria/DeliveryManagerSearchCriteria.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/domain/repository/DeliveryManagerRepository.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/infrastructure/repository/DeliveryCustomRepository.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/infrastructure/repository/DeliveryCustomRepositoryImpl.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/presentation/controller/DeliveryController.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/presentation/controller/DeliveryManagerAdminController.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/presentation/controller/DeliveryManagerController.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/presentation/dto/mapper/DeliveryPresentationMapper.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/presentation/dto/request/DeliveryManagerSearchRequestDto.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/presentation/dto/response/DeliveryManagerAdminResponseDto.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/presentation/dto/response/DeliveryManagerResponseDto.java
Labels: ✏ feat

#218 [Order] - Auditing 수정 #217
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/service/OrderAdminService.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/service/OrderService.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/config/JpaAuditingConfig.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/domain/BaseEntity.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/domain/Order.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/domain/OrderDetail.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/presentation/controller/OrderAdminController.java
Labels: 🛠 fix

#220 [Infra] : Dockerfile 및 docker-compose.yml 파일 생성
  common/Dockerfile
  company-service/Dockerfile
  company-service/build.gradle
  company-service/src/test/java/com/oingmaryho/business/companyservice/application/service/CompanyServiceTest.java
  config-service/Dockerfile
  delivery-service/Dockerfile
  delivery-service/build.gradle
  docker-compose.yml
  eureka-service/Dockerfile
  gateway-service/Dockerfile
  hub-service/Dockerfile
  hub-service/build.gradle
  order-service/Dockerfile
  order-service/build.gradle
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/dto/mapper/OrderApplicationMapper.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/service/OrderService.java
  order-service/src/main/resources/application.yml
  product-service/Dockerfile
  product-service/build.gradle
  slack-service/Dockerfile
  slack-service/build.gradle
  slack-service/settings.gradle
  user-service/Dockerfile
  user-service/build.gradle
Labels: ✏ feat

#222 [Readme] : 오타 수정
  README.md
Labels: 📝 docs

#225 [Company] : test 코드 작성
  company-service/src/main/java/com/oingmaryho/business/companyservice/application/dto/mapper/CompanyApplicationMapper.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/application/dto/request/CompanyCreateRequestServiceDto.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/application/dto/request/CompanySearchRequestServiceDto.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/application/dto/request/CompanyUpdateRequestServiceDto.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/application/dto/response/CompanySearchResponseServiceDto.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/application/service/CompanyAdminService.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/application/service/CompanyService.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/config/interceptor/WebMvcConfig.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/domain/Company.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/domain/CompanySearchCriteria.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/domain/CompanyType.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/domain/repository/CompanyRepository.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/infrastructure/CompanyQueryDslRepository.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/presentation/controller/CompanyAdminController.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/presentation/controller/CompanyController.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/presentation/dto/request/CompanyCreateRequestDto.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/presentation/dto/request/CompanySearchRequestDto.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/presentation/dto/request/CompanyUpdateRequestDto.java
  company-service/src/main/java/com/oingmaryho/business/companyservice/presentation/dto/response/CompanySearchResponseDto.java
  company-service/src/test/java/com/oingmaryho/business/companyservice/application/service/CompanyServiceTest.java
Labels: 🛠 fix, 📑 test

#227 [Order] - 공통 메서드 Helper 분리 #223
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/event/OrderEventHandler.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/service/OrderAdminService.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/service/OrderHelper.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/service/OrderService.java
Labels: ⚙ refactor

#228 [Order] - 공통 클래스 Helper 분리 #223
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/OrderHelper.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/service/OrderAdminService.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/service/OrderService.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/service/queue/OrderQueue.java
Labels: ⚙ refactor

#236 [Order] - 불필요한 주석 삭제 #235
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/OrderHelper.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/event/OrderEventHandler.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/service/OrderAdminService.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/service/OrderService.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/service/queue/OrderQueue.java
Labels: ⚙ refactor

#240 [Order] : Listener 분리하기 #239
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/service/OrderService.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/application/service/queue/OrderQueue.java
  order-service/src/main/java/com/oingmaryho/business/orderservice/infrastructure/adaptor/OrderQueueListener.java
Labels: ⚙ refactor

#243 [Delivery] : Redisson 적용, AOP와 커스텀 어노테이션을 통한 Transaction 최소화
  delivery-service/build.gradle
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/DeliveryLockHelper.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/DeliveryManagerAssignmentHelper.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/dto/mapper/DeliveryApplicationMapper.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/dto/request/DeliveryManagerAssignmentRequestDto.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/dto/request/DeliveryManagerAssignmentRequestServiceDto.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/dto/request/OrderMessageCreationRequestDto.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/dto/request/OrderMessageCreationRequestServiceDto.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/dto/response/DeliveryCreationResponseServiceDto.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/dto/response/DeliveryManagerAssignmentResponseServiceDto.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/event/DeliveryCreationEventHandler.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/service/DeliveryAdminService.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/service/DeliveryLockService.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/service/DeliveryService.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/application/service/RedisLockService.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/config/AopConfig.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/config/RabbitMQConfig.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/config/RedissonConfig.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/domain/entity/Delivery.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/domain/entity/DeliveryRoute.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/exception/ErrorCode.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/exception/LockException.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/infrastructure/AopForTransaction.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/infrastructure/CustomSpringELParser.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/infrastructure/DistributedLock.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/infrastructure/DistributedLockAop.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/infrastructure/repository/DeliveryCustomRepositoryImpl.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/presentation/controller/DeliveryAdminController.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/presentation/controller/DeliveryController.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/presentation/controller/DeliveryManagerAdminController.java
  delivery-service/src/main/java/com/oingmaryho/business/delivery_service/presentation/dto/mapper/DeliveryPresentationMapper.java
Labels: ⚙ refactor
